__all__ = ()

RETURN_CODE_UNSET = -1
RETURN_CODE_SUCCESS = 0
RETURN_CODE_FAILURE = 2

RETURN_CODE_TEST_RUNNER_STOPPED = 4
RETURN_CODE_TEST_RUNNER_INTERRUPTED = 5

RETURN_CODE_TEST_LOCATION_FAILURE = 7
